"""change date column default value

Revision ID: 7c20505e5732
Revises: be9b2055e49d
Create Date: 2026-07-26 11:02:48.179782

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "7c20505e5732"
down_revision: str | None = "be9b2055e49d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
