"""initial unified schema

Revision ID: aa46b7d17339
Revises:
Create Date: 2026-07-11 19:35:08.612762

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa46b7d17339"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alternatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alternative_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alternative_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alternative_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alternative_4", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("correct_alternative", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "correct_alternative BETWEEN 1 AND 4", name="ck_alternatives_correct_range"
        ),
        sa.CheckConstraint(
            "correct_alternative < 4 OR alternative_4 IS NOT NULL",
            name="ck_alternatives_correct_exists",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contextual_texts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "contextual_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contextual_text"),
    )
    op.create_table(
        "statement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "question_command", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_command"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("firebase_uid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("firebase_uid"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_firebase_uid"), ["firebase_uid"], unique=False
        )

    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contextual_text_id", sa.Integer(), nullable=True),
        sa.Column("image_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contextual_text_id"],
            ["contextual_texts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alternative_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alternative_id"],
            ["alternatives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alternative_id"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_uid"), ["uid"], unique=True)

    op.create_table(
        "question_tags",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "tag_id"),
    )
    op.create_table(
        "user_question",
        sa.Column(
            "user_firebase_uid", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CORRECT", "INCORRECT", name="questionstatus"),
            nullable=True,
        ),
        sa.Column("selected_alternative", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_firebase_uid"],
            ["user.firebase_uid"],
        ),
        sa.PrimaryKeyConstraint("user_firebase_uid", "question_id"),
    )
    with op.batch_alter_table("user_question", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_question_user_firebase_uid"),
            ["user_firebase_uid"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_question", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_question_user_firebase_uid"))

    op.drop_table("user_question")
    op.drop_table("question_tags")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_uid"))
        batch_op.drop_index(batch_op.f("ix_questions_level"))

    op.drop_table("questions")
    op.drop_table("media")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_firebase_uid"))

    op.drop_table("user")
    op.drop_table("tags")
    op.drop_table("statement")
    op.drop_table("contextual_texts")
    op.drop_table("alternatives")
    # ### end Alembic commands ###
