"""add date to UserQuestion

Revision ID: be9b2055e49d
Revises: 3f61a7c90d24
Create Date: 2026-07-23 21:33:30.231633

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9b2055e49d'
down_revision: str | None = '3f61a7c90d24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_question_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_question_date'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
